name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: clone ftc-app repository
      run: git clone "https://github.com/FIRST-Tech-Challenge/SkyStone.git"
    - name: move skystone to teamcode
      run: ls -al
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build
